on: { push: { branches: [develop] } }
jobs:
  demo:
    if: github.repository == 'Aver005/pooprusteek-landing'
    uses: Aver005/aaaver-app/.github/workflows/site-release.yml@master
    permissions: { contents: write }
